export default StorageNames = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  CONFIRM_JOB: "CONFIRM_JOB",
  OFFICER_PROFILE: "OFFICER_PROFILE_STAFF",
  INITIAL_APP: "INITIAL_APP",
  UPDATE_ALL_PROFILE: "UPDATE_ALL_PROFILE",
  USER_PROFILE: "USER_PROFILE_STAFF",
  LOCATION_TIME: "LOCATION_TIME",
  ORDER_SERVICE: "ORDER_SERVICE_STAFF",
  MY_ORDER_ACCEPTED: "MY_ORDER_ACCEPTED",
  IS_OLD: "IS_OLD",
};
